services:
  ejs-loader:
      env_file:
        - .env
      build:
          context: .devcontainer
      container_name: "ejs-loader"
      working_dir: /ejs-loader
      volumes:
          - ./:/ejs-loader
          - /ejs-loader/node_modules
          - /ejs-loader/temp
          - ~/.ssh:/home/node/.ssh:ro
          - ./.root_claude:/root/.claude  # /root/.claude（Claude Codeのメモリ・設定）をホストに永続化
        # /tms_shiharai/node_modules nodeのインストールをコンテナ内だけにする設定
        # /tms_shiharai/JaspersoftWorkspace/shiharai/target mvnで生成する内容はコンテナ内
      hostname: "ejs-loader"
      networks:
          - ejs-loader
      tty: true
      #entrypoint:
      #  - /ejs-loader/.devcontainer/initialize.sh
      # command: >
      #   /bin/bash -c '
      #   mkdir /root/.ssh ;
      #   cp /home/node/.ssh/* /root/.ssh;
      #   chmod 0644 /root/.ssh/config ;
      #   chmod 0600 /root/.ssh/id* ;
      #   /ejs-loader/.devcontainer/initialize.sh ;
      #   redis-server /etc/redis/redis.conf'
networks:
    ejs-loader:
